= Hubot-Slack を VPS へインストール

:hp-tags: hubot, slack

## はじめに

hubotを VPS にインストールする手順です。同様のエントリーは多いのですが、記事が古くてうまく動作しない例が多いので改めて書いてみました。

インストールする VPS の OS として CentOS 6.6 で確認しました。他の OSの場合は適宜読み替えてください。

## Node.js, npm  のインストール

Node.js とそのパッケージマネージャーである npm が必要です。Node.js のバージョン管理システムである nvm もインストールします。

現時点で最新である io.js v2.3.3 をインストールします。v2.3.2 にはセキュリティーホールが見つかっているので v2.3.3 以上をインストールしてください。

```
$ git clone https://github.com/creationix/nvm.git ~/.nvm
$ source ~/.nvm/nvm.sh
$ nvm ls-remote
$ nvm install iojs
```

ログイン時に有効にするためには、~/.bashrc, ~/.profile, ~/.zshrc に使用しているシェルに応じて追記します。

```
source ~/.nvm/nvm.sh
nvm default iojs-v2.3.3
```
npm は node.js をインストールしたときにインストールされます。npm を使って npm自信をアップデートできます。執筆時の最新バージョンは 2.12.1 ですが、ベータ版の 3.1.0
が利用できます。

```
$ npm i -g npm@3
$ npm -v
3.1.0
```

## hubot のインストール

hubot をインストールします。hubot は coffee で書かれているため coffee-script もインストールします。

```
$ npm i -g hubot coffee-script
```

## redis のインストール

hubot はデータの永続化に redis を使用するので redis をインストールします。CentOS の場合 EPEL リポジトリが必要です。

```
$ sudo rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
$ sudo yum install -y redis
$ sudo chkconfig redis on
$ sudo service redis start
```

## hubot のひな形作成

hubot のひな形を作成します。昔のバージョンでは hubot -c <botname> で作成しましたが、今は非推奨となり yoeman による生成が推奨されています。






## 参考
npm - https://github.com/npm/npm

pm2 - https://github.com/Unitech/pm2

GitHub製フレームワークHubotの概要とインストール、チャットアプリと連携する基本的な使い方 - http://www.atmarkit.co.jp/ait/articles/1408/20/news035.html

Docker + Yeoman + Hubot + Slack で簡単bot作成 - http://blog.fenneclab.com/docker-yeoman-hubot-slack/



