= Ruby舞鶴で合宿をしました

:hp-tags: ruby



8月29日、30日と舞鶴で Ruby 合宿を行いました。舞鶴をご存じないかもしれませんが、**京都府**です。京都府の北側で海上自衛隊の本部があります。場所はこんなところです。やってきました、舞鶴といいたいところですが、地元なので電車で1駅なのでした。

image::https://drive.google.com/uc?export=view&id=0BxX1sdAOmTicc3Y0VG1GTDRxUUE[]

民家を改造してあってレンタルスペースとして利用できるようになっています。


今回は DDD による開発を行っており、ユーザーストーリーマップによるドメイン分析を行いました。とりあえず思いつくままユーザー要件を並べたのがこちらになります。


image::https://drive.google.com/uc?export=view&id=0BxX1sdAOmTicVzlSMUZpMWx0bWM[]

このホワイトーボードは100均で売っているものをテープで連結したものです。安く仕上がる上に持ち運びまでできるという優れものです。見つけたら買い占めましょう。


その後、時系列に並べ、最低限必要な機能を上に並べていきます。そうするとこのようなシンプルな要求仕様がわかりますので第一スプリントとしてはこの実装を行っていきます。

image::https://drive.google.com/uc?export=view&id=0BxX1sdAOmTicVkh6elJkWHhaQlE[]

1日目の進捗は、アイスブレイク、Slack の作成、リポジトリの作成、ユーザーストーリーマップの作成となりました。


なお、この後懇親会があり、天ぷらをいただいたのですが、スマホを忘れていったので写真はありません。てへぺろ。写真は1日目終了の様子。

image::https://drive.google.com/uc?export=view&id=0BxX1sdAOmTiccVM4N3hvZy0yUTA[]

2日目。

概念モデルを作成し、更に論理モデルへと落とし込みます。このあたりは、分析・設計スキルが要求されるかと思います。


image::https://drive.google.com/uc?export=view&id=0BxX1sdAOmTicWlJBZlhEcnczS3c[]

ここまでで午前が終了。お昼は、山盛りの海鮮丼をいただきました。海鮮を乗せた後の写真を載せるべきでした。味噌汁は当然あら汁です。いやあ、おいしかったです。

image::https://drive.google.com/uc?export=view&id=0BxX1sdAOmTicRC1pdW5xNzdHRGs[]

午後からは、タスクを分割し、論理モデルに従って実装していきます。今回合宿に参加したのは8名なので余裕で実装・・といったところなのですが、テーブルやフィールドのすり合わせから、コントローラーのすり合わせなど意外と時間がかかりました。いろいろあるのがこういった合宿の醍醐味でもありますが、段取り重要ですね。勉強になります。

この開発は RSpec による TDD/BDD ですすめられており、CoverAlls による CI と Slack への通知を行いました。こういったインフラの構築も勉強になりましたし、先駆者の方々の知見を生で得られていい機会となりました。


成果の出たところで KPT を報告し終了です。いやぁ、本当に楽しかった。**Shinosaka.rb** のみなさん、**DDD.rb** のみなさん、**Ruby舞鶴**のみなさんありがとうございました。また、今回お世話になった http://kokin.net/saikaan[宰嘉庵（さいかあん）] さんはリーズナブルな料金でお借りでき、宿泊は出来ないものの Wifi、冷蔵庫も完備されており飲食可能なのでなかなかない良スペースではないかと思いました。

image::https://drive.google.com/uc?export=view&id=0BxX1sdAOmTicYnJrbXgyZ2NIZms[]

いやぁ、またやりたい！それまで勉強するぞ～！
